source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DataBindingLib_Example', :exclusive => true do
  pod "DataBindingLib", :path => "../"
end

target 'DataBindingLib_Tests', :exclusive => true do
  pod "DataBindingLib", :path => "../"

  pod 'FBSnapshotTestCase'
end
